version: '3.8'

services:
  l1_1:
    image: l1_1
    volumes:
      - ./output:/output
    command: cp /app/L1_1.exe /output/L1_1.exe

  l1_2:
    image: l1_2
    volumes:
      - ./output:/output
    command: cp /app/L1_2.exe /output/L1_2.exe
